[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
cryptoscore_factory = "93CjfuYYswDbcjasA1PTUmHhsqFsBQC4JnsiKB8nKJhP"
cryptoscore_market = "94CjfuYYswDbcjasA1PTUmHhsqFsBQC4JnsiKB8nKJhQ"
cryptoscore_dashboard = "95CjfuYYswDbcjasA1PTUmHhsqFsBQC4JnsiKB8nKJhR"

[programs.devnet]
cryptoscore_factory = "5zADKCecxATSEsCuH5MJa1JdfXGeBLNwEYnkCbqdaYmZ"
cryptoscore_market = "BJmMs142koLJvkutSzWchPGn2CJNGqTtGQV5g3Xt87PU"
cryptoscore_dashboard = "DHJASkp8vNuyR5xPSyj1G66xExRjnPBUuUN4QKiTnadZ"

[programs.testnet]
cryptoscore_factory = "TestnetFactoryId1111111111111111111111111"
cryptoscore_market = "TestnetMarketId11111111111111111111111111"
cryptoscore_dashboard = "TestnetDashboardId111111111111111111111111"

[programs.mainnet-beta]
cryptoscore_factory = "MainnetFactoryId111111111111111111111111"
cryptoscore_market = "MainnetMarketId1111111111111111111111111"
cryptoscore_dashboard = "MainnetDashboardId11111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
initialize-factory = "ts-node scripts/initialize-factory.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[test.validator]
url = "http://127.0.0.1:8899"
ledger = ".anchor/test-ledger"
reset = true
verifyFees = false
bind_address = "127.0.0.1"
rpc_port = 8899
faucet_port = 9900
slots_per_epoch = "32"
